version: 2
general:
  branches:
    only:
      - master
      - dev
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: node -v
      - run: sudo npm cache clean -f
      - run: sudo npm install -g n
      - run: sudo n 8.5.0
      - run: node -v
      - run: sudo npm install --global yarn
      - run: yarn --version
