version: 2
general:
  branches:
    only:
      - master
      - dev
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: node -v
      - run: sudo npm cache clean -f
      - run: sudo npm install -g n
      - run: sudo n 8.5.0
      - run: node -v
      - run: sudo npm install --global yarn@1.3.2
      - run: yarn --version
      - run: python --version
      - run: curl -O https://bootstrap.pypa.io/get-pip.py
      - run: python get-pip.py --user
      - run: $PATH
      - run: ~/.local/bin/pip  install awscli --upgrade --user
      - run: aws s3 ls
