version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7
     steps:
       - checkout
       - run: node -v
       - run: sudo npm cache clean -f
       - run: sudo npm install -g n
       - run: sudo n 8.5.0
       - run: node -v
       - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
       - run: yarn --version
